// Code generated by Wire. DO NOT EDIT.

// 本文件由 Google Wire 工具根据 wire.go 自动生成，请勿手动修改。
// 修改依赖注入定义请在 wire.go 中进行，然后运行 `wire` 重新生成。
//
// 生成命令：go generate ./cmd/server
// 手动生成：cd cmd/server && wire

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"gorm.io/gorm"
	"keystonego/internal/handler"
	"keystonego/internal/middleware"
	"keystonego/internal/repository"
	"keystonego/internal/service"
	"keystonego/pkg/response"
)

// Injectors from wire.go:

// InitComponents 由 Wire 自动生成的依赖注入函数。
// 按拓扑顺序依次调用 Provider：Repository → Service → Handler → Router。
func InitComponents(db *gorm.DB) *gin.Engine {
	userRepository := repository.NewUserRepository(db)
	roleRepository := repository.NewRoleRepository(db)
	authService := service.NewAuthService(userRepository, roleRepository, db)
	authHandler := handler.NewAuthHandler(authService)
	userService := service.NewUserService(userRepository, roleRepository)
	userHandler := handler.NewUserHandler(userService)
	menuRepository := repository.NewMenuRepository(db)
	roleService := service.NewRoleService(roleRepository, menuRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	menuService := service.NewMenuService(menuRepository, roleRepository, db)
	menuHandler := handler.NewMenuHandler(menuService)
	permissionRepository := repository.NewPermissionRepository(db)
	permissionService := service.NewPermissionService(permissionRepository, db)
	permissionHandler := handler.NewPermissionHandler(permissionService)
	engine := NewRouter(authHandler, userHandler, roleHandler, menuHandler, permissionHandler, db)
	return engine
}

// wire.go:

// RepositorySet 数据访问层所有 Provider（GORM CRUD 实现）。
var RepositorySet = wire.NewSet(repository.NewUserRepository, repository.NewRoleRepository, repository.NewMenuRepository, repository.NewPermissionRepository)

// ServiceSet 业务逻辑层所有 Provider。
var ServiceSet = wire.NewSet(service.NewAuthService, service.NewUserService, service.NewRoleService, service.NewMenuService, service.NewPermissionService)

// HandlerSet HTTP 控制层所有 Provider。
var HandlerSet = wire.NewSet(handler.NewAuthHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewMenuHandler, handler.NewPermissionHandler)

// NewRouter 创建并配置 Gin 路由引擎。
func NewRouter(
	authHandler *handler.AuthHandler,
	userHandler *handler.UserHandler,
	roleHandler *handler.RoleHandler,
	menuHandler *handler.MenuHandler,
	permHandler *handler.PermissionHandler,
	db *gorm.DB,
) *gin.Engine {
	r := gin.New()

	r.Use(middleware.Recovery())
	r.Use(middleware.Trace())
	r.Use(middleware.Cors())
	r.Use(middleware.Logger())
	r.Use(middleware.Metrics())
	r.Use(middleware.RateLimit())

	r.GET("/metrics", gin.WrapH(promhttp.Handler()))
	r.GET("/healthz", func(c *gin.Context) {
		response.Success(c, gin.H{"status": "ok"})
	})

	r.GET("/readyz", func(c *gin.Context) {
		if err := db.Exec("SELECT 1").Error; err != nil {
			response.Fail(c, 503, "DB disconnected")
			return
		}
		response.Success(c, gin.H{"status": "ready", "db": "connected"})
	})

	r.POST("/api/login", authHandler.Login)
	r.POST("/api/register", authHandler.Register)

	r.POST("/api/v1/auth/refresh", authHandler.Refresh)

	r.POST("/api/v1/auth/login", authHandler.Login)
	r.POST("/api/v1/auth/register", authHandler.Register)

	r.POST("/api/v1/auth/sms/send", authHandler.SendSMS)
	r.POST("/api/v1/auth/sms/login", authHandler.SMSLogin)

	r.GET("/api/v1/auth/oauth/github", authHandler.GitHubOAuth)
	r.GET("/api/v1/auth/oauth/github/callback", authHandler.GitHubCallback)

	r.POST("/api/v1/auth/password/forgot", authHandler.ForgotPassword)
	r.POST("/api/v1/auth/password/reset", authHandler.ResetPassword)

	r.Static("/uploads", "./uploads")

	v1 := r.Group("/api/v1")
	v1.Use(middleware.JWTAuth())
	{
		v1.GET("/user/info", userHandler.GetCurrentUser)
		v1.GET("/user/profile", userHandler.GetProfile)
		v1.PUT("/user/profile", userHandler.UpdateProfile)
		v1.POST("/user/avatar", userHandler.UploadAvatar)
		v1.POST("/auth/logout", authHandler.Logout)
		v1.GET("/auth/channels", authHandler.GetChannels)
		v1.POST("/auth/bind/phone", authHandler.BindPhone)
		v1.POST("/auth/unbind", authHandler.Unbind)
		v1.GET("/monitor/stats", handler.NewMonitorHandler().Stats)
		v1.GET("/user/menus", menuHandler.GetUserMenus)

		users := v1.Group("/users")
		{
			users.GET("", userHandler.List)
			users.GET("/:id", userHandler.Get)
			users.POST("", userHandler.Create)
			users.PUT("/:id", userHandler.Update)
			users.DELETE("/:id", userHandler.Delete)
			users.PUT("/:id/status", userHandler.UpdateStatus)
			users.PUT("/:id/password", userHandler.UpdatePassword)
			users.GET("/:id/roles", userHandler.GetRoles)
			users.PUT("/:id/roles", userHandler.AssignRoles)
		}

		roles := v1.Group("/roles")
		{
			roles.GET("", roleHandler.List)
			roles.GET("/:id", roleHandler.Get)
			roles.POST("", roleHandler.Create)
			roles.PUT("/:id", roleHandler.Update)
			roles.DELETE("/:id", roleHandler.Delete)
			roles.PUT("/:id/status", roleHandler.UpdateStatus)
			roles.GET("/:id/menus", roleHandler.GetMenus)
			roles.PUT("/:id/menus", roleHandler.AssignMenus)
			roles.PUT("/:id/permissions", roleHandler.AssignPermissions)
		}

		menus := v1.Group("/menus")
		{
			menus.GET("", menuHandler.List)
			menus.GET("/tree", menuHandler.List)
			menus.GET("/:id", menuHandler.Get)
			menus.POST("", menuHandler.Create)
			menus.PUT("/:id", menuHandler.Update)
			menus.DELETE("/:id", menuHandler.Delete)
			menus.PUT("/:id/status", menuHandler.UpdateStatus)
		}

		permissions := v1.Group("/permissions")
		{
			permissions.GET("", permHandler.List)
			permissions.GET("/:id", permHandler.Get)
			permissions.POST("", permHandler.Create)
			permissions.PUT("/:id", permHandler.Update)
			permissions.DELETE("/:id", permHandler.Delete)
		}
	}

	return r
}
